Feature/bootstrap
kyutech-programming-club/rails-study pull request #3
Opened 2019-06-19 08:54 UTC by syu-kwsk

flash メッセージをつけました
ヘッダーにログアウトをつけました（常に表示、表示の場合分けできてません）

2019-06-19 09:24 UTC, rkdora approved these changes
flash、できてる。  
ちゃんと、どんなことをしたかも書いてあってよかった。
ただ、プルリクは出来ていないですって言ってだすものじゃない。分からなくて出来ないのか、時間がなくて出来ないのか。
どちらにせよ、あともうちょい。がんば(・∀・)

2019-06-19 09:24 UTC, rkdora commented on app/controllers/sessions_controller.rb
> +      redirect_to root_path, success: "success"
ログイン成功のたびに、flashメッセージはいらないと思うけど、どう思う？

2019-06-19 09:24 UTC, rkdora commented on app/views/layouts/_header.html.erb
> +            <%= link_to 'Logout',logout_path, method: :delete , class: "nav-link" %>
ログアウトしてるのに、ログアウトのリンクあるよ。

2019-06-19 09:24 UTC, rkdora commented on app/views/users/show.html.erb
> +<h1><%= @user.name %>
good。マイページとか書いてたら速攻キレてた。
</h1>、改行せんでいいんやない？

2019-06-19 09:24 UTC, rkdora commented on app/views/layouts/application.html.erb
> +   <%= render "layouts/header" %>
flashは、ヘッダーの下。

2019-06-19 09:26 UTC, rkdora requested changes
間違えて、アプルーブしちゃった。
指摘箇所修正してね

2019-06-19 09:34 UTC, tanacchi commented
りゅーとのコメントが hkimura に似てきてて草
わたるガンバ

2019-06-19 09:35 UTC, rkdora commented
> りゅーとのコメントが hkimura に似てきてて草
> わたるガンバ

意識した笑

2019-06-19 10:25 UTC, rkdora commented
まだ、俺がコメントしたとこでなんもなってないところあるよ。
「resolve conversation」を押しながらリファクタリングするといいね

2019-06-19 10:57 UTC, tetuomi commented on app/controllers/sessions_controller.rb
> +      redirect_to root_path, success: "success"
flashメッセージの他のタイミングが思いつきません...

2019-06-19 11:01 UTC, rkdora commented on app/controllers/sessions_controller.rb
> +      redirect_to root_path, success: "success"
- 新規登録成功時
- ログイン失敗
- ログアウト時（もし、ログイン時つけるのならログアウト時もないと変かなーと）
とか

2019-06-19 11:03 UTC, rkdora commented on app/controllers/sessions_controller.rb
> +      redirect_to root_path, success: "success"
ログイン時にflashつけるかどうかは、最終的には開発者権限なので決めてください(・∀・)
ネット見ると、どっちのパターンもあるみたい

2019-06-19 11:06 UTC, tetuomi commented on app/controllers/sessions_controller.rb
> +      redirect_to root_path, success: "success"
すいません、ログイン成功するたびに、flashメッセージするのを他のタイミングに変えてほしいってことかと思いしました。
他のとこにも、付け足してくれってことですか？

2019-06-19 11:11 UTC, rkdora commented on app/controllers/sessions_controller.rb
> +      redirect_to root_path, success: "success"
あね。
- おいらは、ログイン時のflashなくてもいい派。でも、てったたちのお好きにどうぞ。flashつけるとしても、「success」じゃないほうがいいい「ログインに成功しました」とか？
- ログイン時以外にもつけてみよう

2019-06-19 11:11 UTC, rkdora commented on app/controllers/sessions_controller.rb
> +      redirect_to root_path, success: "success"
これを言いたかった↑

2019-06-19 12:44 UTC, rkdora commented
good!
ログイン失敗時のredirect、よくわかったね。
新規登録成功時も出してみよう

2019-06-19 13:34 UTC, syu-kwsk commented on app/controllers/sessions_controller.rb
> +      redirect_to login_path, danger: "ログイン失敗することに成功しました"
ログイン失敗することに成功した→ログインに失敗しました

2019-06-19 13:35 UTC, tetuomi commented on app/models/user.rb
> +  validates :name, presence: true , uniqueness: true
branch間違えることに成功しました。

2019-06-19 13:38 UTC, syu-kwsk commented on app/controllers/users_controller.rb
> +      redirect_to root_path, success: "ログインに成功しました"
ログインに成功しました　▶　新規完了

2019-06-19 13:40 UTC, syu-kwsk commented on app/controllers/sessions_controller.rb
> +      redirect_to root_path, success: "success"
ログインするたびにflash派です

2019-06-19 13:59 UTC, syu-kwsk commented on app/models/user.rb
> +  validates :name, presence: true , uniqueness: true
わっははっはははははははは

2019-06-19 14:00 UTC, syu-kwsk commented on app/controllers/users_controller.rb
> +      redirect_to root_path, success: "ログインに成功しました"
新規完了　▶　ProChartへようこそ

2019-06-19 15:20 UTC, rkdora commented on app/controllers/users_controller.rb
> +      redirect_to new_user_path, danger: "ユーザー名が重複しているか、書式を満たしていません"
ユーザー名かパスワードが間違っています。でいいと思う

2019-06-20 08:31 UTC, syu-kwsk commented on app/controllers/users_controller.rb
> +      redirect_to new_user_path, danger: "ユーザー名が重複しているか、書式を満たしていません"
その場合、「ユーザー名が間違ってるってどゆこと？」みたいになると思うので、「重複してるお」っていうのはいると思いました。

2019-06-20 09:00 UTC, rkdora commented on app/controllers/users_controller.rb
> +      redirect_to new_user_path, danger: "ユーザー名が重複しているか、書式を満たしていません"
ごめん、ログインと勘違いしてた。おk

2019-06-20 09:02 UTC, rkdora commented
人のユーザー詳細を見るだけで、追放はやばいwww

2019-06-20 15:27 UTC, tetuomi commented
全然違いました笑
がんばりますおTV

2019-06-20 15:50 UTC, rkdora approved these changes
おｋ

2019-06-20 15:51 UTC, merged